### ISSUE TITLE
대회 기간을 3-4일 연장하는 건에 대해 건의 드립니다.

### ISSUE THREAD

**Issue by docosa2** [bab-korea/healthcare-ai-contest#101]
대회 운영진 여러분의 노고에 감사드립니다.

대회에 크고 작은 이슈들이 있지만 비교적 안정화 되는 것 같습니다.

다만 데이타의 규모에 비해 컴퓨팅 리소스와 학습 기간이 짧아 

최소한의 학습도 쉽지 않은 상황입니다. 

또한 대회 규정에 대한 세부 내용도 중간에 문의하면서 진행하는 어려움이 있습니다.

실력있는 팀들이 제대로 능력을 발휘할 수 있도록 3-4일 정도라도 

기간이 연장되었으면 하는 의견입니다. 

감사합니다.

**Comment by kissthedata** [comment]
docosa2님의 의견 이해합니다. 저 또한 많은 스트레스를 받고 있습니다..
그러나, 이 환경 그대로 연장하는 건 의미가 없다 생각합니다.. 연장된 기간에 기존 일정이 있는 분도 있을 것이고, 더욱 많은 Issue와 불만들이 쏟아져 나올거로 예상됩니다. 

빨리 끝내고 다음 대회에서 주최자가 철저한 준비를 하고 다시 여는 게 어떨까 싶네요..
