### ISSUE TITLE
GPU 할당 시간 문의

### ISSUE THREAD

**Issue by IsThereAnyCode** [bab-korea/healthcare-ai-contest#104]
GPU 사용 할당 시간에 대해서 일체 연락 받은 것이 없습니다.

답변 부탁드립니다.

계정명:hjk7625

감사합니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

해당 문의, 카카오채널로 문의 부탁드립니다.

감사합니다.

**Comment by IsThereAnyCode** [comment]
현재 카카오톡 상담 업무가 종료되었다고 뜨며 카톡 전송이 안됩니다.
