### ISSUE TITLE
이 대회도 발표회같은걸 하나요?

### ISSUE THREAD

**Issue by nightandweather** [bab-korea/healthcare-ai-contest#115]
순위권 분들 솔루션을 좀 듣고싶은데 

가능할까요?

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

별도로 발표회는 진행하지 않습니다.

감사합니다.

**Comment by nightandweather** [comment]
줌이라도 했으면 좋았을텐데

아쉽네요
