### ISSUE TITLE
서버의 cuda 버전을 수정해도 괜찮은가요?

### ISSUE THREAD

**Issue by Eumgill98** [bab-korea/healthcare-ai-contest#20]
Build cuda_11.2.r11.2/compiler.29618528_0

현재 서버의 cuda 버전은 11.2로 확인되는데 
편의를 위해서 쿠다버전을 수정해도 괜찮은가요??

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

서버에 기본적으로 셋팅되어있는 버전 변경 및 새로운 라이브러리, 패키지 등을 받으시면 안되고,
이런 경우, 파이토치 혹은 텐서플로우를 권장드립니다.

감사합니다.
