### ISSUE TITLE
GPU서버 문의

### ISSUE THREAD

**Issue by dnjdsxor21** [bab-korea/healthcare-ai-contest#31]
안녕하세요 vscode로 ssh접속을 하려고 시도중인데, 에러가 발생합니다.

현재는 ssh로 들어가면 `/home/{아이디}`로 접속되고, `cd /{아이디}`로 디렉토리 이동해야 합니다. 

**처음에 접속하자마자 `/{아이디}`로 접속되도록 변경해주실 수 있을까요?**

vscode를 통해 접속하려고 하면 `/home/{아이디}`에 vscode-server를 설치하려고 하지만, no space left로 인해, 설치가 불가능합니다.

제 아이디는 `dnjdsxor21` 입니다.

**Comment by nightandweather** [comment]
혹시 어떻게 해결하셨는지 알려주실 수 있나요?

**Comment by dnjdsxor21** [comment]
> 혹시 어떻게 해결하셨는지 알려주실 수 있나요?

위에 문제는 해결하지 못했고, vscode-server 설치위치를 default에서 제 디렉토리로 변경했습니다.
