### ISSUE TITLE
conda 명령어 시 apt_pkg 모듈 없다는 에러 발생

### ISSUE THREAD

**Issue by soohyun3852** [bab-korea/healthcare-ai-contest#33]
miniconda설치 후 가상환경을 생성하려 하였으나 ModuleNotFoundError가 발생합니다. 

apt_pkg를 재설치하라고 하던데, 권한이 없어 설치하지 못했습니다.

감사합니다.

로그:

max2747@g-contest-gpu021:/max2747$ conda
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

root 계정을 제공드릴 수는 없습니다.

필요한 내용을 말씀해주시면, 도움드리겠습니다.
어떤 것이 필요하신가요?

감사합니다.

**Comment by soohyun3852** [comment]
찾아봤는데 해당 모듈을 재설치하라고 하네요.

$ sudo apt remove python3-apt
$ sudo apt install python3-apt

레퍼런스 : https://sncap.tistory.com/m/1115

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

서버 내에 4팀의 다른 팀도 있기 떄문에, 저희측에서 제공해드린 환경에서 하셔야합니다.
영향을 받기 때문에 라이브러리 재설치 등 불가합니다.

가이드 문서를 참조하셔서, 다시 한번 확인해주세요.
블로그를 이용해주셔도 좋습니다.

참고로 콘다는 액티브(활성화) 하셔서 사용하셔야합니다.
가이드 문서, 블로그를 참조해주세요.

감사합니다.

**Comment by soohyun3852** [comment]
conda 명령어 자체가 안먹혀서요. conda 가상환경 active 자체가 안되는 상황입니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

콘다(conda)를 /home/{본 계정명 디렉토리} 가 아닌 /{본 계정명 디렉토리} 에서 설치해주시고, 
콘다 관련해서 재설치 권장드립니다.

감사합니다.

**Comment by soohyun3852** [comment]
max2747@g-contest-gpu021:/max2747$ ls
anaconda3  Dataset  lost+found  Miniconda3-latest-Linux-x86_64.sh

말씀해주신대로 디렉토리 바꿔서 재설치를 수행했으나 같은 에러가 발생합니다.(anaconda3로 설치)

에러메세지 : ModuleNotFoundError: No module named 'apt_pkg'
