### ISSUE TITLE
대회 metric 관련 문의

### ISSUE THREAD

**Issue by wheresmadog** [bab-korea/healthcare-ai-contest#44]
안녕하세요. AIML-K팀의 wheresmadog입니다.

본 대회는 image segmentation + classification으로 이해를 하고 있습니다.
그런데 F1 score로 가린다고 하면, 각 태스크 별 어느 정도의 weight를 가지고 가려내는지 알고 싶습니다.

극단적으로 segmentation에 대한 점수를 따로 뽑아내지 않는다면 classification으로 해석하고 문제를 풀 수도 있습니다.
따라서 정확한 score 산출 방식이 알려져야 할 것 같습니다. 특히 대회 안내에서는 classification에서 사용되는 F1에 대해서는 언급이 되어있지만, segmentation의 dice coefficient 등은 보이지도 않습니다.

**Comment by dnjdsxor21** [comment]
설명이 부족한 부분이 많지만, 일단 segmentation는 아닌 것 같습니다.

저는 'classification(only) -> f1-score 산출'로 이해했습니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

segmentation+classification이 아닌 classification 문제입니다. segmentation에 대한 문제가 아니니 segmentaion의 dice coefficient에 대한 정보는 중요하지 않습니다. 

감사합니다.
