### ISSUE TITLE
디렉토리 초기화 요청

### ISSUE THREAD

**Issue by woojin-choi518** [bab-korea/healthcare-ai-contest#51]
home/twinsno119 디렉토리 초기화 부탁드립니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

"/home/twinsno119" 디렉토리 초기화 되었습니다.

확인 부탁드립니다.

감사합니다.

**Comment by woojin-choi518** [comment]
확인했습니다. 감사합니다!
