### ISSUE TITLE
유동 ip 문제

### ISSUE THREAD

**Issue by Eumgill98** [bab-korea/healthcare-ai-contest#59]
안녕하세요. 현재 집에서 해당 대회를 진행하고 있는데 인터넷이 유동ip로 할당 받아서 
일정 시간이 지나면 ip가 변동 되는 상황이 있는데
변동될때 마다 카톡을 통해서 변경을 문의해도 문제가 없을까요?

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

IP 관련해서는 카카오채널로 문의 부탁드립니다.

감사합니다.
