### ISSUE TITLE
conda 설치 관련 문제

### ISSUE THREAD

**Issue by Geunju-hub** [bab-korea/healthcare-ai-contest#6]
안녕하세요 
서버 접속 후 conda 설치 과정에서 아래와 같은 에러가 발생합니다.
Cannot write to ‘Miniconda3-latest-Linux-x86_64.sh’ (Success).
인터넷 관련 이슈로 생각되는데, 해결 방법을 알려주시면 감사하겠습니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

Cannot write to ‘Miniconda3-latest-Linux-x86_64.sh’ (Success).
(Miniconda3-latest-Linux-x86_64.sh를 작성할 수 없습니다.)

해당 내용만으로는 내용을 확인할 수 없습니다.

감사합니다.

**Comment by Geunju-hub** [comment]
@bab-korea  
구체적인 로그입니다.
--2023-12-11 11:51:50--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK                                                                                                                        ]       0  --.-KB/s    in 0s      
Length: 120986213 (115M) [application/x-sh]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

Miniconda3-latest-Linux   0%[                                ]       0  --.-KB/s    in 0s      


Cannot write to ‘Miniconda3-latest-Linux-x86_64.sh’ (Success).

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

저희는 가이드는 제공드리고, 가상환경 관련 콘다를 이용해서 자유롭게 구축하시면 되지만, 

어떤 명령어를 입력하셨는지 알 수 있을까요?

감사합니다.

**Comment by Geunju-hub** [comment]
@bab-korea  전체 명령어 입력 및 출력 결과입니다.
PS C:\Users\user> ssh ever4red@223.130.162.182
ever4red@223.130.162.182's password: 
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-136-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Dec 11 12:05:07 KST 2023

  System load:  0.01              Processes:           721
  Usage of /:   8.3% of 48.96GB   Users logged in:     13
  Memory usage: 9%                IP address for eth0: 10.10.0.6
  Swap usage:   0%

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

240 packages can be updated.
194 of these updates are security updates.
To see these additional updates run: apt list --upgradable

New release '20.04.6 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Mon Dec 11 11:36:11 2023 from 175.125.54.148
ever4red@g-contest-bastion:~$ ssh ever4red@10.10.1.9
ever4red@10.10.1.9's password: 
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-136-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Dec  6 20:26:19 KST 2023

  System load:  0.0                Processes:              167
  Usage of /:   54.6% of 48.96GB   Users logged in:        1
  Memory usage: 3%                 IP address for eth0:    10.10.1.9
  Swap usage:   0%                 IP address for docker0: 172.17.0.1


241 packages can be updated.
195 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings


*** System restart required ***
Last login: Mon Dec 11 11:36:33 2023 from 10.10.0.6
ever4red@g-contest-gpu004:~$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
--2023-12-11 12:05:52--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 120986213 (115M) [application/x-sh]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

Miniconda3-latest-Linux   0%[                                ]       0  --.-KB/s    in 0s      


Cannot write to ‘Miniconda3-latest-Linux-x86_64.sh’ (Success).

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

작업을 /home/{계정명 디렉토리} 에서 작업해주시고 계신 것 같습니다.

절대경로: /{계정명 디렉토리} 에서 작업해주셔서 용량이 확보가 됩니다.

감사합니다.

**Comment by Geunju-hub** [comment]
@bab-korea 
감사합니다.
경로 변경 후 bash 명령어로 설치 시 저장공간이 부족하다고 나오는데, 이는 어떻게 해결하면 될까요?
아래는 로그입니다.

ever4red@g-contest-gpu004:/$ cd /ever4red
ever4red@g-contest-gpu004:/ever4red$ pwd
/ever4red
ever4red@g-contest-gpu004:/ever4red$ bash Miniconda3-latest-Linux-x86_64.sh

Welcome to Miniconda3 py311_23.10.0-1

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>>
Miniconda3-latest-Linux-x86_64.sh: line 143: cannot create temp file for here-document: No space left on device

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

지금 작업해보시면 될 것 같습니다.

감사합니다.

**Comment by soohyun3852** [comment]
저도 동일한 문제가 발생합니다. 

max2747@g-contest-gpu021:/max2747$ bash Miniconda3-latest-Linux-x86_64.sh

Welcome to Miniconda3 py311_23.10.0-1

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>> 
Miniconda3-latest-Linux-x86_64.sh: line 143: cannot create temp file for here-document: No space left on device

**Comment by dnjdsxor21** [comment]
@bab-korea  안녕하세요 저도 같은 문제 발생합니다.

```
dnjdsxor21@g-contest-gpu009:/dnjdsxor21$ bash Miniconda3-latest-Linux-x86_64.sh

Welcome to Miniconda3 py311_23.10.0-1

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>> 
Miniconda3-latest-Linux-x86_64.sh: line 143: cannot create temp file for here-document: No space left on device
```

**Comment by bab-korea** [comment]
@dnjdsxor21
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

같은 서버 내 인원들 서버 내부에서 작업한 인원들이 있어 /home{본 계정명 디렉토리} 에서 /{본 계정명 디렉토리} 로 이동해놓았습니다.

감사합니다.
