### ISSUE TITLE
서버에 접속이 되지 않고 있습니다. 접속되도 학습이 제대로 진행되지 않습니다.

### ISSUE THREAD

**Issue by docosa2** [bab-korea/healthcare-ai-contest#68]
내용 없음.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

혹시, 계정아이디 알 수 있을까요?

감사합니다.

**Comment by docosa2** [comment]
cnuchips

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

네, 접속은 정상적으로 잘 이루어지는  것으로 보여집니다.
하지만, 현재 /home/cnuchips 작업을 진행을 해주시고 계신데, 절대경로: /cnuchips 에서 작업을 해주셔야합니다.
작업 파일들을 옮겨주시기 바랍니다.

감사합니다.

**Comment by docosa2** [comment]
conda 설치 경로가 /home/cnuchips에서 /cnuchips로 변경이 되지 않습니다.
해결 방법이 있으면 안내 부탁드립니다.

**Comment by docosa2** [comment]
해결되었습니다. 감사합니다.
