### ISSUE TITLE
GPU 서버 사용관련 문의

### ISSUE THREAD

**Issue by Eumgill98** [bab-korea/healthcare-ai-contest#71]
안녕하세요. 현재 GPU서버당 5팀이 공유하고 있는데
만약에 한팀에서 해당 서버의 GPU를 대부분 사용하면 다른 4팀은 사용하지 못하는거 아닌가요?

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

저희도 인지하고 있습니다.
그러한 이유로 인해 GPU서버의 스펙을 높게 사용하고 있습니다.

감사합니다.

**Comment by Eumgill98** [comment]
현재 확인 결과 서버 스펙이 16GB Tesla T4인 것으로 확인되는데,
이 경우 한팀에서 모델 하나만 학습시켜도 나머지 팀은 학습 진행이 어렵습니다.

만약에 한팀만 계속사용한다면 나머지 팀은 학습을 한번도 진행 못할 수 있지 않을까요?

**Comment by Junhyuk93** [comment]
다른 팀 사용자께서 GPU 용량을 모두 할당한 채 계속 사용하고 계셔서 저희의 모델을 올릴 수가 없습니다.

**Comment by Eumgill98** [comment]
확인했는데 다른 사용자분이 학습을 진행하고 있는거 같습니다

**Comment by Jeon-jisu** [comment]
저희도 다른 사용자분이 있어서 학습을 못하고 있는 상황입니다.

**Comment by jeongiin** [comment]
저희도 마찬가지입니다.

**Comment by jeongiin** [comment]
pid까지 확인해 본 결과 한 사람만 사용해도 다른 사람이 아예 사용을 못합니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

GPU 관련 이슈 있으신 분들 계정 아이디 알 수 있을까요?

감사합니다.

**Comment by Eumgill98** [comment]
wjdghcks02 입니다
