### ISSUE TITLE
no space left on device error가 뜹니다

### ISSUE THREAD

**Issue by nightandweather** [bab-korea/healthcare-ai-contest#8]
안녕하세요 역사는밤에쓰여진다 팀 이강훈입니다

콘다에 jupyter notebook 을 설치하려고 하는데 에러가 생겨 설치가 안됩니다

확인 부탁드립니다

이강훈 드림

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

현재 /home/{계정명 디렉토리} 경로에서 작업 중이신 것으로 판단됩니다.

해당 디렉토리에서 작업하시면 안되고, /{계정명 디렉토리} 디렉토리에서 작업하셔야합니다

제가 /{계정명 디렉토리}해당디렉토리로 파일 옮기는 것을 도와드리겠습니다.

감사합니다.

**Comment by nightandweather** [comment]
파일 옮겨져 있는것을 확인하였습니다.

이게 미니 콘다를 /home/계정명 디렉토리로 설치를 안하고 상위 폴더로 설치를 해버리면

1 os당5명이 들어가 있는데 다른 사람들의 conda에 영향이 가지 않을까요..?

**Comment by nightandweather** [comment]
그냥 제 /dlrkdgns1324 폴더에 있는 내용을 dataset 말고 전부 삭제해주시면 감사하겠습니다

miniconda 를 재설치 해보겠습니다.

**Comment by bab-korea** [comment]
@nightandweather 
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

그냥 제 /dlrkdgns1324 폴더에 있는 내용을 dataset 말고 전부 삭제해주시면 감사하겠습니다

miniconda 를 재설치 해보겠습니다.

>>>>>>>>>>>>>>>>>>>>>>

네 감사합니다.

감사합니다.

**Comment by nightandweather** [comment]
네 지워주신것 확인하였습니다 

감사합니다.
