### ISSUE TITLE
최종 산출물에 대한 문의

### ISSUE THREAD

**Issue by Junhyuk93** [bab-korea/healthcare-ai-contest#88]
#81 
위 이슈 글에서 언급하신 것처럼 최종 산출물 txt에 f1 score만 작성되도 된다고 하셨는데
검증을 위한 (파일명  / Ground Truths / predict)은 필요 없는건가요?
그리고 weight 파일을 통해 성능이 재현되는지에 대한 테스트도 같이 진행하시는지 궁금합니다.

**Comment by gyupro** [comment]
최종산출물은 validation datset에 대하여 metric. 계산하는건가요?

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

검증단이 테스트 검증을 진행하지만, Ground Truth, predict는 제출하지 않아도 됩니다.
