### ISSUE TITLE
bastion 접속 불가: connection closed 

### ISSUE THREAD

**Issue by Tenzzi** [bab-korea/healthcare-ai-contest#9]
안녕하세요. 플레이아이디어랩 팀 소속 이상록입니다. 
문제와 궁금증이 있어서 문의 드립니다

1. 접속 문제 - 터미널에서 접속을 시도하면 connection closed라고 뜨고 접속이 안 됩니다.
아래는 커맨드창에서 입력한 커맨드와 실행 결과입니다.

(base) isanglogs-MacBook-Air:~ lsr$ ssh bb1939@223.130.162.182
bb1939@223.130.162.182's password: 
Connection to 223.130.162.182 closed.

2. task가 정확히 무엇인가요? 충치 여부를 판단하는 이진 분류인지, 치아 segmentation까지 해당되는 건지 궁금합니다.
3.  사용하는 모델 종류가 공지에 적혀 있는 대로 efficient net 또는 resnet이어야 하나요?
4. 데이터 예시를 확인할 수 있을까요? 한 장 정도의 예시도 좋고 설명을 해주셔도 좋을 것 같습니다

**Comment by Tenzzi** [comment]
추가로, 파이토치 설치 과정에서 no space left on device가 발생해서, bb1939 디렉토리 이동해서 conda 가상환경을 생성하고, bb1939 디렉토리 안의 tmp 폴더로 TMPDIR과 PIP_CACHE_DIR의 경로를 변경해주었는데 이렇게 하는 게 맞을까요?

**Comment by bab-korea** [comment]
@Tenzzi 
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

 1.이진분류로 판단하면 됩니다.
 2. resnet, efficient은 참고 모델이므로, 다른모델을 사용해도 괜찮습니다.
3. 데이터예시는 샘플로 제공하는 데이터 말고는 추가로 예시를 들만한게 없습니다.

감사합니다.

**Comment by Tenzzi** [comment]
감사합니다!
