### ISSUE TITLE
현재 정해진 시간에 들어왔으나 다른 팀이 GPU를 쓰고 있습니다. 다른 사용자의 프로세스를 종료시켜주세요.

### ISSUE THREAD

**Issue by novemddd** [bab-korea/healthcare-ai-contest#94]
현재 gpu2개를 거의 다 쓰고 있는 상태여서 학습코드를 돌리지도 못하고 있습니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

혹시, 계정아이디 알 수 있을까요?

감사합니다.

**Comment by novemddd** [comment]
@bab-korea
아직까지도 대처가 이루어지지 않았는데 혹시 언제쯤 가능할까요?

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

한번 재확인 부탁드립니다.

감사합니다.

**Comment by novemddd** [comment]
확인했습니다. 감사합니다. 그런데 아래글을 보니 추가 연장이 가능한 것 같은데 그렇게 하면 그 뒤에 팀은 또 못쓰게 될 텐데 그렇지만 전 현재 40분 가량 코드를 돌리지도 못했습니다. 이 부분에 대해서는 시간을 더 부여 가능할까요?

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

정해진 시간은 지켜주셔야합니다.
해당 내용 카톡으로 문의주시면 답변드리겠습니다.

감사합니다.
