### ISSUE TITLE
GPU 사용에 관해서

### ISSUE THREAD

**Issue by Eumgill98** [bab-korea/healthcare-ai-contest#96]
현재 GPU 사용에 대해서 시간을 할당해주신걸로 확인했습니다.
그런데 서버 GPU 사용에 대해서 모니터링해보니 
한팀이 3일 동안 혼자서 GPU를 전부 사용하고 계십니다.
**(현재 그 팀의 할당 시간인지는 모르겠지만  특정 할당 파트가 지났는데도 사용하고 있습니다.)**

**따라서 다른팀의 경우 이팀으로 인해서 3일 동안 한번도 학습을 진행할 수 없었습니다.**
이 경우에 다른팀들에 대해서 공정성의 문제가 있지 않을까요??

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

혹시, 계정아이디 알 수 있을까요?

감사합니다.

**Comment by Eumgill98** [comment]
wjdghcks02
입니다

**Comment by Eumgill98** [comment]
혹시 해결방법이 있을까요?
