### ISSUE TITLE
서버 접속이 제한되었습니다.

### ISSUE THREAD

**Issue by Junhyuk93** [bab-korea/healthcare-ai-contest#99]
서버 접속시 Connection time out이 뜨는데 확인 부탁드립니다.

akznsk1 계정입니다.

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

현재, 지정된 시간이 아닌 다른 사용자 분의 지정 시간이기에 지정된 시간에만 이용해주시기 바랍니다.
양해 부탁드립니다.

감사합니다.

**Comment by Junhyuk93** [comment]
지정 시간인지 테이블을 어디서 확인할 수 있나요?

**Comment by bab-korea** [comment]
안녕하세요. 2023 구강이미지 합성데이터 헬스케어 AI 경진대회 운영팀입니다.

카카오 채널로 문의 부탁드립니다.

감사합니다.
